const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const MARGIN = 54;

function sanitizeFilePart(value) {
  return String(value || 'student')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/gi, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();
}

function toPdfHex(value) {
  const text = String(value ?? '');
  const bytes = [0xfe, 0xff];
  for (let index = 0; index < text.length; index += 1) {
    const code = text.charCodeAt(index);
    bytes.push((code >> 8) & 0xff, code & 0xff);
  }
  return `<${bytes.map((byte) => byte.toString(16).padStart(2, '0')).join('')}>`;
}

function wrapText(value, maxChars = 74) {
  const words = String(value || '').split(/\s+/).filter(Boolean);
  const lines = [];
  let line = '';

  words.forEach((word) => {
    const candidate = line ? `${line} ${word}` : word;
    if (candidate.length > maxChars && line) {
      lines.push(line);
      line = word;
    } else {
      line = candidate;
    }
  });

  if (line) lines.push(line);
  return lines.length ? lines : [''];
}

function textCommand(text, x, y, size = 11, font = 'F1') {
  return `BT /${font} ${size} Tf ${x} ${y} Td ${toPdfHex(text)} Tj ET`;
}

function lineCommand(x1, y1, x2, y2) {
  return `${x1} ${y1} m ${x2} ${y2} l S`;
}

function buildPdfContent(convention) {
  const content = [];
  const id = convention.id || 'draft';
  const status = convention.status || 'ready';
  let y = PAGE_HEIGHT - 58;

  content.push('0.93 0.97 0.96 rg 0 0 595 842 re f');
  content.push('1 1 1 rg 38 34 519 760 re f');
  content.push('0.09 0.28 0.29 RG 2 w 38 34 519 760 re S');
  content.push(textCommand('MyImpact', MARGIN, y, 22, 'F2'));
  content.push(textCommand('Convention de mission citoyenne', MARGIN, y - 30, 18, 'F2'));
  content.push(textCommand(`Reference: #${id}`, 400, y, 11));
  content.push(textCommand(`Status: ${status}`, 400, y - 18, 11));
  y -= 72;

  content.push('0.90 0.96 0.94 rg 54 680 487 48 re f');
  content.push(textCommand('Generated convention packet', MARGIN + 14, 704, 13, 'F2'));
  content.push(textCommand('Prepared for school, student, and NGO signature review.', MARGIN + 14, 688, 10));
  y = 642;

  const fields = [
    ['Student', convention.studentName],
    ['Student email', convention.studentEmail],
    ['NGO / organization', convention.ngoName],
    ['Mission period', `${convention.startDate || 'TBD'} to ${convention.endDate || 'TBD'}`],
    ['Target hours', `${convention.targetHours || 0} hours`]
  ];

  fields.forEach(([label, value]) => {
    content.push(textCommand(label, MARGIN, y, 10, 'F2'));
    content.push(textCommand(value || 'TBD', 190, y, 11));
    content.push(lineCommand(MARGIN, y - 10, 540, y - 10));
    y -= 34;
  });

  y -= 10;
  content.push(textCommand('Mission description', MARGIN, y, 12, 'F2'));
  y -= 22;
  wrapText(convention.missionDescription, 86).forEach((line) => {
    content.push(textCommand(line, MARGIN, y, 11));
    y -= 17;
  });

  y -= 22;
  content.push(textCommand('Signature placeholders', MARGIN, y, 12, 'F2'));
  y -= 52;

  [
    ['Student signature', MARGIN],
    ['School administrator', 230],
    ['NGO representative', 390]
  ].forEach(([label, x]) => {
    content.push(lineCommand(x, y, x + 130, y));
    content.push(textCommand(label, x, y - 16, 9));
    content.push(textCommand('Date:', x, y - 32, 9));
  });

  content.push(textCommand('Generated by ImpactBeta for prototype review. Confirm legal wording before production use.', MARGIN, 74, 9));
  return content.join('\n');
}

export function buildConventionPdfBlob(convention) {
  const content = buildPdfContent(convention);
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>',
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`
  ];

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return new Blob([pdf], { type: 'application/pdf' });
}

export function getConventionPdfFilename(convention) {
  return `convention-${convention.id || 'draft'}-${sanitizeFilePart(convention.studentName)}.pdf`;
}

export function downloadConventionPdf(convention) {
  const blob = buildConventionPdfBlob(convention);
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = getConventionPdfFilename(convention);
  document.body.appendChild(link);
  link.click();
  window.URL.revokeObjectURL(url);
  document.body.removeChild(link);
}
