-- Supabase schema and row-level security for the ImpactBeta workflow app.
-- Run in the Supabase SQL editor after creating the project. The React app
-- expects these tables plus Supabase Auth email/password enabled.

do $$
begin
  create type public.user_role as enum ('school_admin', 'student', 'ngo_admin');
exception
  when duplicate_object then null;
end
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text not null,
  role public.user_role not null default 'student',
  organization_name text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  student_name text not null,
  student_email text not null,
  ngo_name text not null,
  mission_description text not null,
  start_date date not null,
  end_date date not null,
  target_hours numeric not null check (target_hours > 0),
  status text not null default 'pending' check (status in ('pending', 'validated', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conventions (
  id bigint generated by default as identity primary key,
  application_id bigint references public.applications(id) on delete cascade,
  student_name text not null,
  student_email text not null,
  ngo_name text not null,
  mission_description text not null,
  start_date date not null,
  end_date date not null,
  target_hours numeric not null check (target_hours > 0),
  status text not null default 'ready' check (status in ('ready', 'draft', 'active')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.applications enable row level security;
alter table public.conventions enable row level security;

create or replace function public.current_user_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid()
$$;

create or replace function public.current_user_org()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select organization_name from public.profiles where id = auth.uid()
$$;

create policy "profiles are visible to owners and school admins"
  on public.profiles for select
  using (id = auth.uid() or public.current_user_role() = 'school_admin');

create policy "users can create their profile"
  on public.profiles for insert
  with check (id = auth.uid());

create policy "owners and school admins can maintain profiles"
  on public.profiles for update
  using (id = auth.uid() or public.current_user_role() = 'school_admin')
  with check (id = auth.uid() or public.current_user_role() = 'school_admin');

create policy "school admins can read all applications"
  on public.applications for select
  using (public.current_user_role() = 'school_admin');

create policy "students can read their applications"
  on public.applications for select
  using (public.current_user_role() = 'student' and student_email = auth.jwt() ->> 'email');

create policy "ngo admins can read their applications"
  on public.applications for select
  using (
    public.current_user_role() = 'ngo_admin'
    and ngo_name ilike '%' || public.current_user_org() || '%'
  );

create policy "students can create their applications"
  on public.applications for insert
  with check (
    public.current_user_role() = 'student'
    and student_email = auth.jwt() ->> 'email'
  );

create policy "school admins can validate or reject applications"
  on public.applications for update
  using (public.current_user_role() = 'school_admin')
  with check (public.current_user_role() = 'school_admin');

create policy "school admins can read all conventions"
  on public.conventions for select
  using (public.current_user_role() = 'school_admin');

create policy "students can read their conventions"
  on public.conventions for select
  using (public.current_user_role() = 'student' and student_email = auth.jwt() ->> 'email');

create policy "ngo admins can read their conventions"
  on public.conventions for select
  using (
    public.current_user_role() = 'ngo_admin'
    and ngo_name ilike '%' || public.current_user_org() || '%'
  );

create policy "school admins can create conventions"
  on public.conventions for insert
  with check (public.current_user_role() = 'school_admin');

create policy "school admins can update conventions"
  on public.conventions for update
  using (public.current_user_role() = 'school_admin')
  with check (public.current_user_role() = 'school_admin');
